version: '3.0'

services:
  am-db:
    image: hmcts/am-db
    container_name: am-db
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - am-lib-testing-service-network
    ports:
      - 5600:5432
    env_file:
      - .env

networks:
  am-lib-testing-service-network:
    driver: bridge
